import XCTest
@testable import BlusherCore

final class BlusherTests:XCTestCase {
    func hand(_ left:Bool, gap:CGFloat=0.15, curled:Bool=true, confidence:Float=1)->HandPose { let x:CGFloat=left ? 0.35:0.65, direction:CGFloat=left ? 1:-1, wrist=CGPoint(x:x-direction*0.08,y:0.35); return HandPose(wrist:Joint(wrist,confidence:confidence),indexMCP:Joint(CGPoint(x:x-direction*0.1,y:0.5),confidence:confidence),indexPIP:Joint(CGPoint(x:x-direction*0.04,y:0.51),confidence:confidence),indexTip:Joint(CGPoint(x:0.5-direction*gap/2,y:0.5),confidence:confidence),middleTip:Joint(CGPoint(x:x-direction*0.04,y:curled ? 0.39:0.65),confidence:confidence),ringTip:Joint(CGPoint(x:x-direction*0.07,y:curled ? 0.38:0.64),confidence:confidence),littleTip:Joint(CGPoint(x:x-direction*0.09,y:curled ? 0.37:0.61),confidence:confidence)) }
    func testValidGestureScoresHigh(){XCTAssertGreaterThan(GestureScorer.score([hand(true),hand(false)]),0.68)}
    func testOneHandFails(){XCTAssertEqual(GestureScorer.score([hand(true)]),0)}
    func testLowConfidenceFails(){XCTAssertEqual(GestureScorer.score([hand(true,confidence:0.1),hand(false)]),0)}
    func testExtendedFingersReduceScore(){XCTAssertLessThan(GestureScorer.score([hand(true,curled:false),hand(false,curled:false)]),GestureScorer.score([hand(true),hand(false)]))}
    func testStateHysteresis(){var s=GestureStateMachine(); XCTAssertFalse(s.update(score:1,time:0)); XCTAssertTrue(s.update(score:1,time:0.2)); XCTAssertTrue(s.update(score:0,time:0.3)); XCTAssertFalse(s.update(score:0,time:0.7))}
    func testAnimationFrameIndependent(){var a=EffectAnimator(); _=a.update(active:true,time:0); XCTAssertEqual(a.update(active:true,time:0.15),0.5,accuracy:0.001); XCTAssertEqual(a.update(active:true,time:0.3),1,accuracy:0.001); XCTAssertEqual(a.update(active:false,time:0.55),0.5,accuracy:0.001)}
    func testVisionCornersAndCenter(){let m=FrameCoordinateMapper(size:.init(width:1920,height:1080));let cases:[(CGPoint,CGPoint)]=[(.init(x:0,y:0),.init(x:0,y:0)),(.init(x:1,y:0),.init(x:1920,y:0)),(.init(x:0,y:1),.init(x:0,y:1080)),(.init(x:1,y:1),.init(x:1920,y:1080)),(.init(x:0.5,y:0.5),.init(x:960,y:540)),(.init(x:0.25,y:0.25),.init(x:480,y:270))];for(i,e)in cases{let p=m.visionPointToCanonical(i);XCTAssertEqual(p.x,e.x,accuracy:0.001);XCTAssertEqual(p.y,e.y,accuracy:0.001)}}
    func testNonZeroExtent(){let m=FrameCoordinateMapper(extent:.init(x:10,y:20,width:100,height:200)),p=m.visionPointToCanonical(.init(x:0.25,y:0.75));XCTAssertEqual(p.x,35);XCTAssertEqual(p.y,170)}
    func testFaceRelativeLandmark(){let m=FrameCoordinateMapper(size:.init(width:1000,height:500)),face=CGRect(x:0.2,y:0.1,width:0.4,height:0.6),p=m.faceRelativeToCanonical(.init(x:0.25,y:0.75),face:face);XCTAssertEqual(p.x,300,accuracy:0.001);XCTAssertEqual(p.y,275,accuracy:0.001)}
    func testDisplayMirror(){let m=FrameCoordinateMapper(size:.init(width:1920,height:1080));let a=m.canonicalToDisplay(.init(x:480,y:540),displaySize:.init(width:960,height:540),mode:.fit,mirrored:false),b=m.canonicalToDisplay(.init(x:480,y:540),displaySize:.init(width:960,height:540),mode:.fit,mirrored:true);XCTAssertEqual(a.x,240);XCTAssertEqual(b.x,720);XCTAssertEqual(a.y,270);XCTAssertEqual(b.y,270)}
    func testAspectFillCrop(){let m=FrameCoordinateMapper(size:.init(width:1920,height:1080));let center=m.canonicalToDisplay(.init(x:960,y:540),displaySize:.init(width:400,height:400),mode:.fill,mirrored:false);XCTAssertEqual(center.x,200,accuracy:0.001);XCTAssertEqual(center.y,200,accuracy:0.001)}
    func testFacialBasisHorizontal(){let f=FaceModel(leftEye:.init(x:100,y:200),rightEye:.init(x:200,y:200),nose:.init(x:150,y:150),mouth:.init(x:150,y:120),faceRect:.zero);XCTAssertEqual(f.leftCheek.y,158,accuracy:0.01);XCTAssertLessThan(f.leftCheek.x,100);XCTAssertGreaterThan(f.rightCheek.x,200)}
    func testFacialBasisRotatesAndScales(){let a=FaceModel(leftEye:.init(x:0,y:0),rightEye:.init(x:100,y:100),nose:.init(x:60,y:20),mouth:.init(x:70,y:0),faceRect:.zero),b=FaceModel(leftEye:.init(x:0,y:0),rightEye:.init(x:200,y:200),nose:.init(x:120,y:40),mouth:.init(x:140,y:0),faceRect:.zero);XCTAssertEqual(b.scale,a.scale*2,accuracy:0.001);XCTAssertEqual(a.angle,.pi/4,accuracy:0.001)}
    func testSmoothingFrameRateIndependent(){let a=FaceModel(leftEye:.zero,rightEye:.init(x:100,y:0),nose:.init(x:50,y:-50),mouth:.init(x:50,y:-80),faceRect:.zero),b=FaceModel(leftEye:.init(x:100,y:0),rightEye:.init(x:200,y:0),nose:.init(x:150,y:-50),mouth:.init(x:150,y:-80),faceRect:.zero);let once=a.smoothed(toward:b,deltaTime:0.1),twice=a.smoothed(toward:b,deltaTime:0.05).smoothed(toward:b,deltaTime:0.05);XCTAssertEqual(once.leftEye.x,twice.leftEye.x,accuracy:0.001)}
}
