import AVFoundation
import BlusherCore
import CoreImage
import CoreImage.CIFilterBuiltins
import OSLog
import SwiftUI
import SystemExtensions
import Vision

final class CameraModel: NSObject, ObservableObject, AVCaptureVideoDataOutputSampleBufferDelegate, OSSystemExtensionRequestDelegate, @unchecked Sendable {
    struct ExtensionStatus { var text: String; var color: Color }
    @Published var preview: CGImage?
    @Published var status="Starting…"
    @Published var blushing=false
    @Published var devices:[AVCaptureDevice]=[]
    @Published var selectedID=""
    @Published var effectEnabled=true
    @Published var diagnosticsEnabled=false
    @Published var metrics=""
    @Published var extensionStatus=ExtensionStatus(text:"Camera Extension not verified",color:.orange)
    private let log=Logger(subsystem:"com.nixboi42.Blusher",category:"camera"), session=AVCaptureSession(), queue=DispatchQueue(label:"com.nixboi42.Blusher.camera",qos:.userInitiated), ci=CIContext(options:[.cacheIntermediates:false,.priorityRequestLow:true])
    private let handRequest:VNDetectHumanHandPoseRequest={let r=VNDetectHumanHandPoseRequest();r.maximumHandCount=2;return r}(), faceRequest=VNDetectFaceLandmarksRequest()
    private var machine=GestureStateMachine(),animator=EffectAnimator(),faceModel:FaceModel?,lastFaceTime=0.0,lastModelTime=0.0,lastVision=0.0
    private var metricsStart=CACurrentMediaTime(),inputFrames=0,outputFrames=0,visionFrames=0,visionTotal=0.0,renderTotal=0.0,loggedFormat=false

    func start(){AVCaptureDevice.requestAccess(for:.video){[weak self] granted in guard let self else{return};guard granted else{DispatchQueue.main.async{self.status="Camera access denied"};return};self.refresh();DispatchQueue.main.asyncAfter(deadline:.now()+0.1){self.configure(self.selectedID.isEmpty ? self.devices.first?.uniqueID:nil)}}}
    func refresh(){let found=AVCaptureDevice.DiscoverySession(deviceTypes:[.builtInWideAngleCamera,.external],mediaType:.video,position:.unspecified).devices.filter{!$0.localizedName.contains("Blusher")};DispatchQueue.main.async{self.devices=found;if self.selectedID.isEmpty{self.selectedID=found.first?.uniqueID ?? ""}}}
    func select(_ id:String){configure(id)}
    private func configure(_ id:String?){queue.async{self.session.stopRunning();self.session.inputs.forEach(self.session.removeInput);self.session.outputs.forEach(self.session.removeOutput);guard let device=self.devices.first(where:{$0.uniqueID==id}) ?? self.devices.first,let input=try? AVCaptureDeviceInput(device:device)else{return};self.session.beginConfiguration();self.session.sessionPreset = .hd1280x720;if self.session.canAddInput(input){self.session.addInput(input)};let output=AVCaptureVideoDataOutput();output.videoSettings=[kCVPixelBufferPixelFormatTypeKey as String:kCVPixelFormatType_32BGRA];output.alwaysDiscardsLateVideoFrames=true;output.setSampleBufferDelegate(self,queue:self.queue);if self.session.canAddOutput(output){self.session.addOutput(output)};if let c=output.connection(with:.video){c.automaticallyAdjustsVideoMirroring=false;c.isVideoMirrored=false};self.session.commitConfiguration();self.session.startRunning();DispatchQueue.main.async{self.status="Camera active"}}}

    func captureOutput(_ output:AVCaptureOutput,didOutput sampleBuffer:CMSampleBuffer,from connection:AVCaptureConnection){autoreleasepool{guard let px=CMSampleBufferGetImageBuffer(sampleBuffer)else{return};let now=CACurrentMediaTime(),w=CVPixelBufferGetWidth(px),h=CVPixelBufferGetHeight(px);inputFrames += 1;if !loggedFormat{loggedFormat=true;let rotation=connection.videoRotationAngle;log.info("Canonical frame \(w)x\(h), Vision orientation=up, capture mirrored=\(connection.isVideoMirrored), rotation=\(rotation,format:.fixed(precision:1))°, display mirror=final only")};if now-lastVision>=0.125{lastVision=now;analyze(px,extent:CGRect(x:0,y:0,width:w,height:h),now:now)};let started=CACurrentMediaTime();let canonical=CIImage(cvPixelBuffer:px);let visibility=max(0,min(1,(0.65-(now-lastFaceTime))/0.35));let intensity=(effectEnabled ? animator.update(active:blushing,time:now):0)*visibility;var processed=canonical;if let model=faceModel{if intensity>0{processed=renderBlush(processed,model:model,intensity:intensity)};if diagnosticsEnabled{processed=renderDiagnostics(processed,model:model)}};let display=processed.oriented(.upMirrored);guard let cg=ci.createCGImage(display,from:display.extent)else{return};renderTotal += CACurrentMediaTime()-started;outputFrames += 1;DispatchQueue.main.async{self.preview=cg};publishMetrics(now)}}
    private func analyze(_ px:CVPixelBuffer,extent:CGRect,now:Double){let started=CACurrentMediaTime();do{try VNImageRequestHandler(cvPixelBuffer:px,orientation:.up).perform([handRequest,faceRequest]);let active=machine.update(score:GestureScorer.score((handRequest.results ?? []).compactMap(Self.pose)),time:now);if let o=faceRequest.results?.max(by:{$0.boundingBox.width<$1.boundingBox.width}),let raw=Self.makeFaceModel(o,mapper:FrameCoordinateMapper(extent:extent)){faceModel=faceModel?.smoothed(toward:raw,deltaTime:now-lastModelTime) ?? raw;lastModelTime=now;lastFaceTime=now};DispatchQueue.main.async{self.blushing=active}}catch{Logger(subsystem:"com.nixboi42.Blusher",category:"vision").error("Vision failed: \(error.localizedDescription)")};visionTotal += CACurrentMediaTime()-started;visionFrames += 1}

    private static func center(_ region:VNFaceLandmarkRegion2D?)->CGPoint?{guard let region,region.pointCount>0 else{return nil};let p=region.normalizedPoints.reduce(CGPoint.zero){CGPoint(x:$0.x+$1.x,y:$0.y+$1.y)},n=CGFloat(region.pointCount);return CGPoint(x:p.x/n,y:p.y/n)}
    private static func makeFaceModel(_ o:VNFaceObservation,mapper:FrameCoordinateMapper)->FaceModel?{let box=o.boundingBox,l=o.landmarks;let le=center(l?.leftEye) ?? CGPoint(x:0.32,y:0.62),re=center(l?.rightEye) ?? CGPoint(x:0.68,y:0.62),n=center(l?.nose) ?? CGPoint(x:0.5,y:0.43),m=center(l?.outerLips) ?? CGPoint(x:0.5,y:0.25);return FaceModel(leftEye:mapper.faceRelativeToCanonical(le,face:box),rightEye:mapper.faceRelativeToCanonical(re,face:box),nose:mapper.faceRelativeToCanonical(n,face:box),mouth:mapper.faceRelativeToCanonical(m,face:box),faceRect:mapper.visionRectToCanonical(box))}
    private static func pose(_ o:VNHumanHandPoseObservation)->HandPose?{func j(_ n:VNHumanHandPoseObservation.JointName)->BlusherCore.Joint?{guard let p=try? o.recognizedPoint(n)else{return nil};return .init(p.location,confidence:p.confidence)};guard let w=j(.wrist),let m=j(.indexMCP),let p=j(.indexPIP),let t=j(.indexTip),let mt=j(.middleTip),let rt=j(.ringTip),let lt=j(.littleTip)else{return nil};return HandPose(wrist:w,indexMCP:m,indexPIP:p,indexTip:t,middleTip:mt,ringTip:rt,littleTip:lt)}
    private func renderBlush(_ input:CIImage,model:FaceModel,intensity:Double)->CIImage{[model.leftCheek,model.rightCheek].reduce(input){base,center in let radius=model.scale*0.30,g=CIFilter.radialGradient();g.center=center;g.radius0=Float(radius*0.08);g.radius1=Float(radius);g.color0=CIColor(red:1,green:0.10,blue:0.30,alpha:0.42*intensity);g.color1=CIColor(red:1,green:0.25,blue:0.42,alpha:0);let x=CGAffineTransform(translationX:center.x,y:center.y).rotated(by:model.angle).scaledBy(x:1,y:0.58).translatedBy(x:-center.x,y:-center.y);return g.outputImage!.transformed(by:x).cropped(to:input.extent).composited(over:base)}}
    private func renderDiagnostics(_ input:CIImage,model:FaceModel)->CIImage{var image=input;func overlay(_ color:CIColor,_ r:CGRect){image=CIImage(color:color).cropped(to:r).composited(over:image)};let f=model.faceRect,t:CGFloat=3;overlay(.green,.init(x:f.minX,y:f.minY,width:f.width,height:t));overlay(.green,.init(x:f.minX,y:f.maxY-t,width:f.width,height:t));overlay(.green,.init(x:f.minX,y:f.minY,width:t,height:f.height));overlay(.green,.init(x:f.maxX-t,y:f.minY,width:t,height:f.height));for(p,c)in[(model.leftEye,CIColor.cyan),(model.rightEye,.cyan),(model.nose,.yellow),(model.mouth,.white),(model.leftCheek,.red),(model.rightCheek,.red)]{overlay(c,.init(x:p.x-5,y:p.y-5,width:10,height:10))};return image}
    private func publishMetrics(_ now:Double){let elapsed=now-metricsStart;guard elapsed>=5 else{return};let text=String(format:"in %.1f fps • out %.1f fps • Vision %.1f Hz / %.1f ms • render %.1f ms",Double(inputFrames)/elapsed,Double(outputFrames)/elapsed,Double(visionFrames)/elapsed,visionTotal/Double(max(1,visionFrames))*1000,renderTotal/Double(max(1,outputFrames))*1000);log.info("Performance: \(text,privacy:.public)");DispatchQueue.main.async{self.metrics=text};metricsStart=now;inputFrames=0;outputFrames=0;visionFrames=0;visionTotal=0;renderTotal=0}

    func activateExtension(){guard Bundle.main.bundleURL.path.hasPrefix("/Applications/")else{extensionStatus = .init(text:"Move Blusher to Applications first",color:.red);return};let r=OSSystemExtensionRequest.activationRequest(forExtensionWithIdentifier:"com.nixboi42.Blusher.CameraExtension",queue:.main);r.delegate=self;OSSystemExtensionManager.shared.submitRequest(r)}
    func request(_ request:OSSystemExtensionRequest,didFinishWithResult result:OSSystemExtensionRequest.Result){extensionStatus = .init(text:"Blusher Camera activated",color:.green)}
    func request(_ request:OSSystemExtensionRequest,didFailWithError error:Error){extensionStatus = .init(text:error.localizedDescription,color:.red)}
    func requestNeedsUserApproval(_ request:OSSystemExtensionRequest){extensionStatus = .init(text:"Approve Blusher Camera in System Settings",color:.orange)}
    func request(_ request:OSSystemExtensionRequest,actionForReplacingExtension existing:OSSystemExtensionProperties,withExtension ext:OSSystemExtensionProperties)->OSSystemExtensionRequest.ReplacementAction{.replace}
}
